import {
  QuestionnaireSchemaSnapshot,
  QuestionType,
} from '../questionnaire.types';

export const FACULTY_OUT_OF_CLASSROOM_SCHEMA_V1: QuestionnaireSchemaSnapshot = {
  meta: {
    questionnaireType: 'FACULTY_OUT_OF_CLASSROOM',
    scoringModel: 'SECTION_WEIGHTED',
    version: 1,
    maxScore: 5,
  },
  sections: [
    {
      id: 'sec-oc-1',
      title: 'I. Punctual Submission of:',
      order: 1,
      weight: 15,
      questions: [
        {
          id: 'q-oc-1-1',
          text: 'Updated Course Guide',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PUNCTUAL_SUBMISSION',
          required: true,
          order: 1,
        },
        {
          id: 'q-oc-1-2',
          text: 'Major Exams (TOS & TQ)',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PUNCTUAL_SUBMISSION',
          required: true,
          order: 2,
        },
        {
          id: 'q-oc-1-3',
          text: 'Class Records',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PUNCTUAL_SUBMISSION',
          required: true,
          order: 3,
        },
        {
          id: 'q-oc-1-4',
          text: 'Course Outline',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PUNCTUAL_SUBMISSION',
          required: true,
          order: 4,
        },
        {
          id: 'q-oc-1-5',
          text: 'Result-oriented',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PUNCTUAL_SUBMISSION',
          required: true,
          order: 5,
        },
      ],
    },
    {
      id: 'sec-oc-2',
      title:
        'II. Quality of Submitted Requirements (neat, clear, well-organized):',
      order: 2,
      weight: 15,
      questions: [
        {
          id: 'q-oc-2-1',
          text: 'Updated Syllabus/Course Guide',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'QUALITY_REQUIREMENTS',
          required: true,
          order: 1,
        },
        {
          id: 'q-oc-2-2',
          text: 'Major Exams (TOS & TQ)',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'QUALITY_REQUIREMENTS',
          required: true,
          order: 2,
        },
        {
          id: 'q-oc-2-3',
          text: 'Class Records',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'QUALITY_REQUIREMENTS',
          required: true,
          order: 3,
        },
        {
          id: 'q-oc-2-4',
          text: 'Course Outline',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'QUALITY_REQUIREMENTS',
          required: true,
          order: 4,
        },
      ],
    },
    {
      id: 'sec-oc-3',
      title: 'III. Adherence to School Policies:',
      order: 3,
      weight: 15,
      questions: [
        {
          id: 'q-oc-3-1',
          text: 'Wearing of Decent Attire',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'SCHOOL_POLICIES',
          required: true,
          order: 1,
        },
        {
          id: 'q-oc-3-2',
          text: 'Attendance',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'SCHOOL_POLICIES',
          required: true,
          order: 2,
        },
        {
          id: 'q-oc-3-3',
          text: 'Begins and ends the class on time',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'SCHOOL_POLICIES',
          required: true,
          order: 3,
        },
        {
          id: 'q-oc-3-4',
          text: 'Observance of regulation on leaves, absences, and official business',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'SCHOOL_POLICIES',
          required: true,
          order: 4,
        },
      ],
    },
    {
      id: 'sec-oc-4',
      title:
        'IV. Attendance/Participation in School/Department Activities/Functions:',
      order: 4,
      weight: 15,
      questions: [
        {
          id: 'q-oc-4-1',
          text: 'School Meetings',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PARTICIPATION',
          required: true,
          order: 1,
        },
        {
          id: 'q-oc-4-2',
          text: 'Faculty Development Activities',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PARTICIPATION',
          required: true,
          order: 2,
        },
        {
          id: 'q-oc-4-3',
          text: 'Program/Activities (as coach, trainer, etc.)',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PARTICIPATION',
          required: true,
          order: 3,
        },
        {
          id: 'q-oc-4-4',
          text: 'Department meeting',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PARTICIPATION',
          required: true,
          order: 4,
        },
      ],
    },
    {
      id: 'sec-oc-5',
      title: "V. Supervision of Students' Out-of-Classroom Activities:",
      order: 5,
      weight: 10,
      questions: [
        {
          id: 'q-oc-5-1',
          text: 'Curricular activities',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'STUDENT_SUPERVISION',
          required: true,
          order: 1,
        },
        {
          id: 'q-oc-5-2',
          text: 'Co-curricular activities',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'STUDENT_SUPERVISION',
          required: true,
          order: 2,
        },
      ],
    },
    {
      id: 'sec-oc-6',
      title: 'VI. Professional/Personal Growth:',
      order: 6,
      weight: 15,
      questions: [
        {
          id: 'q-oc-6-1',
          text: 'Seminar/Workshop for Professional development',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONAL_GROWTH',
          required: true,
          order: 1,
        },
        {
          id: 'q-oc-6-2',
          text: 'Personal and Interpersonal development',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONAL_GROWTH',
          required: true,
          order: 2,
        },
        {
          id: 'q-oc-6-3',
          text: 'Membership in Professional Organization, Research, Community Extension, Civic and religious Organizations',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONAL_GROWTH',
          required: true,
          order: 3,
        },
      ],
    },
    {
      id: 'sec-oc-7',
      title:
        'VII. Involvement in Research and Community Service/Outreach Activities:',
      order: 7,
      weight: 15,
      questions: [
        {
          id: 'q-oc-7-1',
          text: 'Research activities',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'RESEARCH_COMMUNITY',
          required: true,
          order: 1,
        },
        {
          id: 'q-oc-7-2',
          text: 'Community activities',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'RESEARCH_COMMUNITY',
          required: true,
          order: 2,
        },
        {
          id: 'q-oc-7-3',
          text: 'Civic/religious activities',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'RESEARCH_COMMUNITY',
          required: true,
          order: 3,
        },
      ],
    },
  ],
  qualitativeFeedback: {
    enabled: true,
    required: false,
    maxLength: 1000,
  },
};
