import {
  QuestionnaireSchemaSnapshot,
  QuestionType,
} from '../questionnaire.types';

export const FACULTY_FEEDBACK_SCHEMA_V1: QuestionnaireSchemaSnapshot = {
  meta: {
    questionnaireType: 'FACULTY_FEEDBACK',
    scoringModel: 'SECTION_WEIGHTED',
    version: 1,
    maxScore: 5,
  },
  sections: [
    {
      id: 'sec-fb-1',
      title: 'I. Preparation',
      order: 1,
      weight: 15,
      questions: [
        {
          id: 'q-fb-1-1',
          text: 'Prepares the course syllabus and presents it to the students at the beginning of the semester.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PREPARATION',
          required: true,
          order: 1,
        },
        {
          id: 'q-fb-1-2',
          text: 'Orients the students on the grading system, course requirements, and class policies.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PREPARATION',
          required: true,
          order: 2,
        },
        {
          id: 'q-fb-1-3',
          text: 'Follows the topic outline in the course syllabus.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PREPARATION',
          required: true,
          order: 3,
        },
        {
          id: 'q-fb-1-4',
          text: 'Comes to class well-prepared with instructional materials and learning activities.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PREPARATION',
          required: true,
          order: 4,
        },
        {
          id: 'q-fb-1-5',
          text: 'Demonstrates mastery of the subject matter.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PREPARATION',
          required: true,
          order: 5,
        },
      ],
    },
    {
      id: 'sec-fb-2',
      title: 'II. Teaching and Learning Process',
      order: 2,
      weight: 35,
      questions: [
        {
          id: 'q-fb-2-1',
          text: 'Starts and ends the class on time.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 1,
        },
        {
          id: 'q-fb-2-2',
          text: 'Discusses the intended learning outcomes at the beginning of each lesson.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 2,
        },
        {
          id: 'q-fb-2-3',
          text: 'Presents topics in a clear and organized manner.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 3,
        },
        {
          id: 'q-fb-2-4',
          text: 'Uses varied and appropriate teaching strategies and methods.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 4,
        },
        {
          id: 'q-fb-2-5',
          text: 'Integrates real-life examples and current trends in the discussion.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 5,
        },
        {
          id: 'q-fb-2-6',
          text: 'Encourages active student participation and collaboration.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 6,
        },
        {
          id: 'q-fb-2-7',
          text: 'Utilizes instructional materials and technology effectively.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 7,
        },
        {
          id: 'q-fb-2-8',
          text: 'Provides opportunities for critical thinking and problem solving.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 8,
        },
        {
          id: 'q-fb-2-9',
          text: 'Gives clear and specific instructions for learning activities.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 9,
        },
        {
          id: 'q-fb-2-10',
          text: 'Relates lessons to the intended learning outcomes of the course.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 10,
        },
        {
          id: 'q-fb-2-11',
          text: 'Adjusts teaching pace according to the needs of the students.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 11,
        },
        {
          id: 'q-fb-2-12',
          text: 'Summarizes key points at the end of each lesson.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 12,
        },
        {
          id: 'q-fb-2-13',
          text: 'Motivates students to learn beyond the classroom.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 13,
        },
        {
          id: 'q-fb-2-14',
          text: 'Engages students in meaningful and relevant learning experiences.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 14,
        },
        {
          id: 'q-fb-2-15',
          text: 'Provides supplementary learning materials and references.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 15,
        },
        {
          id: 'q-fb-2-16',
          text: 'Promotes inclusive learning by respecting diverse perspectives.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 16,
        },
        {
          id: 'q-fb-2-17',
          text: 'Encourages questions and provides satisfactory answers.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHING_LEARNING',
          required: true,
          order: 17,
        },
      ],
    },
    {
      id: 'sec-fb-3',
      title: 'III. Assessment',
      order: 3,
      weight: 25,
      questions: [
        {
          id: 'q-fb-3-1',
          text: 'Gives assessments that are aligned with the intended learning outcomes.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 1,
        },
        {
          id: 'q-fb-3-2',
          text: 'Uses varied assessment methods (e.g., quizzes, projects, presentations).',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 2,
        },
        {
          id: 'q-fb-3-3',
          text: 'Provides clear rubrics or criteria for graded activities.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 3,
        },
        {
          id: 'q-fb-3-4',
          text: 'Returns graded assessments and feedback in a timely manner.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 4,
        },
        {
          id: 'q-fb-3-5',
          text: 'Provides constructive feedback that helps improve student performance.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 5,
        },
        {
          id: 'q-fb-3-6',
          text: 'Ensures fairness and objectivity in grading.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 6,
        },
        {
          id: 'q-fb-3-7',
          text: 'Discusses assessment results with students.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 7,
        },
        {
          id: 'q-fb-3-8',
          text: 'Uses assessment results to improve teaching and learning.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'ASSESSMENT',
          required: true,
          order: 8,
        },
      ],
    },
    {
      id: 'sec-fb-4',
      title: 'IV. Learning Environment',
      order: 4,
      weight: 10,
      questions: [
        {
          id: 'q-fb-4-1',
          text: 'Creates a safe and conducive learning environment.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'LEARNING_ENVIRONMENT',
          required: true,
          order: 1,
        },
        {
          id: 'q-fb-4-2',
          text: 'Treats students with respect and fairness.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'LEARNING_ENVIRONMENT',
          required: true,
          order: 2,
        },
        {
          id: 'q-fb-4-3',
          text: 'Encourages open communication and mutual respect among students.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'LEARNING_ENVIRONMENT',
          required: true,
          order: 3,
        },
        {
          id: 'q-fb-4-4',
          text: 'Maintains discipline and order in the classroom.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'LEARNING_ENVIRONMENT',
          required: true,
          order: 4,
        },
        {
          id: 'q-fb-4-5',
          text: 'Utilizes the LMS (Learning Management System) for course delivery and communication.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'LEARNING_ENVIRONMENT',
          required: true,
          order: 5,
        },
        {
          id: 'q-fb-4-6',
          text: 'Makes learning resources available and accessible through online platforms.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'LEARNING_ENVIRONMENT',
          required: true,
          order: 6,
        },
        {
          id: 'q-fb-4-7',
          text: 'Is available for consultation outside of class hours.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'LEARNING_ENVIRONMENT',
          required: true,
          order: 7,
        },
      ],
    },
    {
      id: 'sec-fb-5',
      title: "V. Teacher's Professionalism",
      order: 5,
      weight: 15,
      questions: [
        {
          id: 'q-fb-5-1',
          text: 'Demonstrates professionalism in appearance and conduct.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 1,
        },
        {
          id: 'q-fb-5-2',
          text: 'Shows genuine concern for the academic growth of students.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 2,
        },
        {
          id: 'q-fb-5-3',
          text: 'Maintains confidentiality of student records and information.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 3,
        },
        {
          id: 'q-fb-5-4',
          text: 'Upholds ethical standards in teaching and assessment.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 4,
        },
        {
          id: 'q-fb-5-5',
          text: 'Shows willingness to improve teaching practices.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 5,
        },
        {
          id: 'q-fb-5-6',
          text: 'Handles student concerns and complaints professionally.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 6,
        },
        {
          id: 'q-fb-5-7',
          text: 'Demonstrates commitment to continuous professional development.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 7,
        },
        {
          id: 'q-fb-5-8',
          text: 'Promotes the vision, mission, and core values of the institution.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 8,
        },
        {
          id: 'q-fb-5-9',
          text: 'Serves as a role model to students.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 9,
        },
        {
          id: 'q-fb-5-10',
          text: 'Demonstrates respect for institutional policies and guidelines.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 10,
        },
        {
          id: 'q-fb-5-11',
          text: 'Participates in school activities and community engagement.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 11,
        },
        {
          id: 'q-fb-5-12',
          text: 'Observes proper channels for communication and conflict resolution.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'PROFESSIONALISM',
          required: true,
          order: 12,
        },
      ],
    },
  ],
  qualitativeFeedback: {
    enabled: true,
    required: false,
    maxLength: 1000,
  },
};
