import {
  QuestionnaireSchemaSnapshot,
  QuestionType,
} from '../questionnaire.types';

export const FACULTY_IN_CLASSROOM_SCHEMA_V1: QuestionnaireSchemaSnapshot = {
  meta: {
    questionnaireType: 'FACULTY_IN_CLASSROOM',
    scoringModel: 'SECTION_WEIGHTED',
    version: 1,
    maxScore: 5,
  },
  sections: [
    {
      id: 'sec-ic-1',
      title: 'I. Planning',
      order: 1,
      sections: [
        {
          id: 'sec-ic-1-a',
          title: 'A. Intended Learning Outcomes (ILO)',
          order: 1,
          weight: 15,
          questions: [
            {
              id: 'q-ic-1-a-1',
              text: 'States the intended learning outcomes (ILO) at the beginning of the lesson.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ILO',
              required: true,
              order: 1,
            },
            {
              id: 'q-ic-1-a-2',
              text: 'Writes the ILO on the board or presents it visually.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ILO',
              required: true,
              order: 2,
            },
            {
              id: 'q-ic-1-a-3',
              text: 'Aligns the ILO with the course syllabus.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ILO',
              required: true,
              order: 3,
            },
            {
              id: 'q-ic-1-a-4',
              text: "Uses action verbs aligned with Bloom's Taxonomy in stating the ILO.",
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ILO',
              required: true,
              order: 4,
            },
            {
              id: 'q-ic-1-a-5',
              text: 'Ensures that the ILO is measurable and attainable within the lesson period.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ILO',
              required: true,
              order: 5,
            },
          ],
        },
        {
          id: 'sec-ic-1-b',
          title: 'B. Contents',
          order: 2,
          weight: 15,
          questions: [
            {
              id: 'q-ic-1-b-1',
              text: 'Selects content that is relevant to the intended learning outcomes.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'CONTENTS',
              required: true,
              order: 1,
            },
            {
              id: 'q-ic-1-b-2',
              text: 'Organizes and sequences the content logically.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'CONTENTS',
              required: true,
              order: 2,
            },
            {
              id: 'q-ic-1-b-3',
              text: 'Integrates current and relevant examples in the content.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'CONTENTS',
              required: true,
              order: 3,
            },
          ],
        },
      ],
    },
    {
      id: 'sec-ic-2',
      title: 'II. Teaching Performance',
      order: 2,
      sections: [
        {
          id: 'sec-ic-2-a',
          title: 'A. Preparation Phase',
          order: 1,
          weight: 10,
          questions: [
            {
              id: 'q-ic-2-a-1',
              text: 'Reviews the previous lesson to connect it with the new topic.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PREPARATION_PHASE',
              required: true,
              order: 1,
            },
            {
              id: 'q-ic-2-a-2',
              text: 'Uses motivational activities to engage students at the start of the lesson.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PREPARATION_PHASE',
              required: true,
              order: 2,
            },
            {
              id: 'q-ic-2-a-3',
              text: "Checks students' prior knowledge before introducing new concepts.",
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PREPARATION_PHASE',
              required: true,
              order: 3,
            },
            {
              id: 'q-ic-2-a-4',
              text: 'Prepares instructional materials appropriate for the lesson.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PREPARATION_PHASE',
              required: true,
              order: 4,
            },
          ],
        },
        {
          id: 'sec-ic-2-b',
          title: 'B. Presentation-Development Phase',
          order: 2,
          weight: 15,
          questions: [
            {
              id: 'q-ic-2-b-1',
              text: 'Presents the lesson in a clear and systematic manner.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PRESENTATION',
              required: true,
              order: 1,
            },
            {
              id: 'q-ic-2-b-2',
              text: 'Uses varied teaching strategies appropriate to the lesson.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PRESENTATION',
              required: true,
              order: 2,
            },
            {
              id: 'q-ic-2-b-3',
              text: 'Integrates technology and multimedia in the lesson delivery.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PRESENTATION',
              required: true,
              order: 3,
            },
            {
              id: 'q-ic-2-b-4',
              text: 'Encourages higher-order thinking through questioning techniques.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PRESENTATION',
              required: true,
              order: 4,
            },
            {
              id: 'q-ic-2-b-5',
              text: 'Provides opportunities for students to apply learned concepts.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PRESENTATION',
              required: true,
              order: 5,
            },
            {
              id: 'q-ic-2-b-6',
              text: 'Facilitates student-centered learning activities.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'PRESENTATION',
              required: true,
              order: 6,
            },
          ],
        },
        {
          id: 'sec-ic-2-c',
          title: 'C. Assessment Phase',
          order: 3,
          weight: 15,
          questions: [
            {
              id: 'q-ic-2-c-1',
              text: 'Conducts formative assessment to check student understanding during the lesson.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ASSESSMENT_PHASE',
              required: true,
              order: 1,
            },
            {
              id: 'q-ic-2-c-2',
              text: 'Uses assessment results to adjust instruction as needed.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ASSESSMENT_PHASE',
              required: true,
              order: 2,
            },
            {
              id: 'q-ic-2-c-3',
              text: 'Provides feedback on student performance during and after the lesson.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'ASSESSMENT_PHASE',
              required: true,
              order: 3,
            },
          ],
        },
        {
          id: 'sec-ic-2-d',
          title: 'D. Classroom Management',
          order: 4,
          weight: 10,
          questions: [
            {
              id: 'q-ic-2-d-1',
              text: 'Manages class time effectively.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'CLASSROOM_MGMT',
              required: true,
              order: 1,
            },
            {
              id: 'q-ic-2-d-2',
              text: 'Maintains discipline and orderliness in the classroom.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'CLASSROOM_MGMT',
              required: true,
              order: 2,
            },
            {
              id: 'q-ic-2-d-3',
              text: 'Creates a positive and inclusive learning atmosphere.',
              type: QuestionType.LIKERT_1_5,
              dimensionCode: 'CLASSROOM_MGMT',
              required: true,
              order: 3,
            },
          ],
        },
      ],
    },
    {
      id: 'sec-ic-3',
      title: 'III. Teacher Qualities',
      order: 3,
      weight: 20,
      questions: [
        {
          id: 'q-ic-3-1',
          text: 'Demonstrates mastery of the subject matter.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHER_QUALITIES',
          required: true,
          order: 1,
        },
        {
          id: 'q-ic-3-2',
          text: 'Communicates clearly and effectively.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHER_QUALITIES',
          required: true,
          order: 2,
        },
        {
          id: 'q-ic-3-3',
          text: 'Shows enthusiasm and passion for teaching.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHER_QUALITIES',
          required: true,
          order: 3,
        },
        {
          id: 'q-ic-3-4',
          text: 'Demonstrates patience and understanding towards students.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHER_QUALITIES',
          required: true,
          order: 4,
        },
        {
          id: 'q-ic-3-5',
          text: 'Maintains professional appearance and demeanor.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHER_QUALITIES',
          required: true,
          order: 5,
        },
        {
          id: 'q-ic-3-6',
          text: 'Shows respect and fairness to all students.',
          type: QuestionType.LIKERT_1_5,
          dimensionCode: 'TEACHER_QUALITIES',
          required: true,
          order: 6,
        },
      ],
    },
  ],
  qualitativeFeedback: {
    enabled: true,
    required: false,
    maxLength: 1000,
  },
};
