export enum PipelineStatus {
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  EMBEDDING_CHECK = 'EMBEDDING_CHECK',
  SENTIMENT_ANALYSIS = 'SENTIMENT_ANALYSIS',
  SENTIMENT_GATE = 'SENTIMENT_GATE',
  TOPIC_MODELING = 'TOPIC_MODELING',
  GENERATING_RECOMMENDATIONS = 'GENERATING_RECOMMENDATIONS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
